# Generated by Django 5.2.15 on 2026-08-04 04:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

REGISTRATION_CONSENT_POLICY_NAME = "organizations_registration_consent_tenant_isolation"
REGISTRATION_VERIFICATION_POLICY_NAME = "organizations_registration_verification_tenant_isolation"
RUNTIME_ROLE_NAME = "moviqo_runtime"
TENANT_SETTING_NAME = "moviqo.current_organization_id"


def _quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _current_tenant_uuid_sql() -> str:
    return f"NULLIF(current_setting({_quote_literal(TENANT_SETTING_NAME)}, true), '')::uuid"


def _tenant_table_policy_sql(*, table_name: str, policy_name: str) -> str:
    tenant_expression = _current_tenant_uuid_sql()
    return f"""
ALTER TABLE {_quote_identifier(table_name)} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {_quote_identifier(table_name)} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS {_quote_identifier(policy_name)} ON {_quote_identifier(table_name)};
CREATE POLICY {_quote_identifier(policy_name)}
    ON {_quote_identifier(table_name)}
    USING (organization_id = {tenant_expression})
    WITH CHECK (organization_id = {tenant_expression});
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {_quote_identifier(table_name)}
    TO {_quote_identifier(RUNTIME_ROLE_NAME)};
"""


def apply_registration_rls(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return

    statements = (
        _tenant_table_policy_sql(
            table_name="organizations_registration_consent",
            policy_name=REGISTRATION_CONSENT_POLICY_NAME,
        ),
        _tenant_table_policy_sql(
            table_name="organizations_registration_verification",
            policy_name=REGISTRATION_VERIFICATION_POLICY_NAME,
        ),
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def noop_reverse(_apps, _schema_editor) -> None:
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_moviqouser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='registration_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='moviqouser',
            name='currency_code',
            field=models.CharField(default='COP', max_length=8),
        ),
        migrations.AddField(
            model_name='moviqouser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='moviqouser',
            name='preferred_language',
            field=models.CharField(default='es', max_length=8),
        ),
        migrations.AddField(
            model_name='moviqouser',
            name='region_code',
            field=models.CharField(default='CO', max_length=8),
        ),
        migrations.AddField(
            model_name='moviqouser',
            name='timezone_name',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency_code',
            field=models.CharField(default='COP', max_length=8),
        ),
        migrations.AddField(
            model_name='organization',
            name='preferred_language',
            field=models.CharField(default='es', max_length=8),
        ),
        migrations.AddField(
            model_name='organization',
            name='region_code',
            field=models.CharField(default='CO', max_length=8),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone_name',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.CreateModel(
            name='OrganizationRegistrationConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('terms_version', models.CharField(max_length=64)),
                ('privacy_version', models.CharField(max_length=64)),
                ('prohibited_data_acknowledged', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_consents', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_registration_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_registration_consent',
            },
        ),
        migrations.CreateModel(
            name='RegistrationVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_verifications', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_verifications', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_registration_verification',
            },
        ),
        migrations.RunPython(apply_registration_rls, noop_reverse),
    ]
