# Generated by Django 5.2.15 on 2026-08-04 12:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_membership_registration_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationregistrationconsent",
            name="privacy_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationregistrationconsent",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="InitialRegistrationCommandResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ("normalized_email", models.CharField(max_length=254)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=128)),
                ("result_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "organizations_initial_registration_command_result",
            },
        ),
        migrations.AddConstraint(
            model_name="initialregistrationcommandresult",
            constraint=models.UniqueConstraint(
                fields=("normalized_email", "idempotency_key"),
                name="organizations_initial_registration_command_result_unique",
            ),
        ),
    ]
