# Generated by Django 5.2.15 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_team_tenant_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="registration_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="registration_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=32,
            ),
        ),
    ]
